version: "3"

networks:

 spidy_web:
  driver: bridge

# how to name volumes

volumes:

 wordpress:
  driver: local
  driver_opts:
   type: 'volume' # ???
   o: 'bind'
   device: '/home/epresa/data/wordpress'

 mariadb:
  driver: local
  driver_opts:
   type: 'volume'
   o: 'bind' # Bind Mounts are volumes that mount on a path to the host, and they can be modified by other processes outside docker.
   device: '/home/epresa/data/mariadb'

services:

 mariadb:
  container_name: mariadb
  image: mariadb
  networks:
  - spidy_web
  build: ./requirements/mariadb
  env_file: .env
  volumes:
  - mariadb:/var/lib/mysql
  restart: unless-stopped

 nginx:
  container_name: nginx
  image: nginx
  volumes:
  - wordpress:/var/www/wordpress
  networks:
  - spidy_web
  depends_on:
  - wordpress
  build: ./requirements/nginx
  env_file: .env
  ports:
  - "443:443"
  restart: on-failure

 wordpress:
  container_name: wordpress
  image: wordpress
  env_file: .env
  volumes:
  - wordpress:/var/www/wordpress
  networks:
  - spidy_web
  build: ./requirements/wordpress
  depends_on:
  - mariadb
  restart: on-failure
  expose:
  - "9000"
